# https://just.systems

target := './ -regex ".*\.\(c\|h\|cpp\|hpp\|ino\)$"'

target:
    find {{ target }} -type f;

deps:
    cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

clang-tidy:
    run-clang-tidy -quiet -p ./build -header-filter='^(include|src)/(?!proto/)' '^src/(?!proto/).*' '^include/.*';

format:
    find {{ target }} -exec clang-format -i {} +;

format-check:
    find {{ target }} -exec clang-format --Werror --dry-run -i {} +;

build profile='default':
    arduino-cli compile -m {{profile}} .

