[tools]
clang-format = "latest"
arduino-cli = "latest"
just = "latest"
"pipx:cppcheck" = "latest"

[tasks.lint]
run = ["just format-check", "just cppcheck"]

[tasks.format]
run = "just format"

[tasks.build]
run = "arduino-cli compile --fqbn arduino:zephyr:unoq ."
