[tools]
clang-format = "latest"
arduino-cli = "latest"
just = "latest"

[tasks.lint]
run = "just format-check"

[tasks.format]
run = "just format"

[tasks.build]
run = "arduino-cli compile --fqbn arduino:zephyr:unoq ."
