[tools]
clang-format = "latest"


[tasks.lint]
run = """
clang-format \
--Werror --dry-run \
pinout.h sketch.ino
"""

[tasks.format]
run = """
clang-format \
-i \
pinout.h sketch.ino
"""

[tasks.compile]
run = "arduino-cli compile --fqbn arduino:zephyr:unoq ."
