experimental_monorepo_root = true

[monorepo]
config_roots = ["sketch", "python"]

[settings]
experimental = true
minimum_release_age = "3d"

[tasks.toml_lint]
run = "tombi lint"

[tasks.toml_format]
run = "tombi format"

[tasks.format]
depends = ["//*:format", "toml_format"]

[tasks.lint]
depends = ["//*:lint", "toml_lint"]

[tasks.compile]
depends = ["sketch:compile"]

[tools]
tombi = "latest"
