name: Sketch

on:
  push:
    branches: [main]
    paths:
      - "sketch/**"
      - ".github/workflows/sketch.yml"
  pull_request:
    branches: [main]
    paths:
      - "sketch/**"
      - ".github/workflows/sketch.yml"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          working_directory: sketch
      - name: Run clang-format
        run: mise lint
        working-directory: sketch

  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache Arduino Dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.arduino15
            ~/Arduino
          key: arduino-${{ hashFiles('sketch/**') }}
          restore-keys: |
            arduino-

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install Platforms
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:zephyr

      - name: Compile Sketch
        run: arduino-cli compile -m default .
        working-directory: sketch
